version: '3.8'

services:
  db:
    image: postgres:13  # Use the official PostgreSQL image
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    environment:
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: django_password
      POSTGRES_DB: django_db

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
