# Generated by Django 4.2.18 on 2025-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletoppings',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pizzamasterpieces',
            name='toppings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='availabletoppings',
            name='topping_name',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pizzamasterpieces',
            name='pizza_name',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
