# Generated by Django 4.2.18 on 2025-02-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_availabletoppings_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzamasterpieces',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizzamasterpieces',
            name='toppings',
            field=models.ManyToManyField(to='app.availabletoppings'),
        ),
    ]
